[package]
name = "test-shadow"
version = "0.1.0"
edition = "2018"

[dependencies]
shadow-rs = "^0.16.3"

[build-dependencies]
shadow-rs = "^0.16.3"

[patch.crates-io]
tzdb = { path = "./tzdb/" }

[workspace]
members = [".", "tzdb"]
