[package]
name = "tzdb"
version = "0.4.6"
edition = "2018"

[dependencies]
orig_tzdb = { package = "tzdb", path = "../.." }

[features]
default = ["by-name", "list", "local", "std", "fallback", "now"]
alloc = []
binary = []
by-name = []
fallback = []
list = []
local = []
now = []
std = ["alloc"]
