[package]
name = "make-tzdb"
version = "0.0.0"
edition = "2021"
authors = ["René Kijewski <crates.io@k6i.de>"]
repository = "https://github.com/Kijewski/tzdb"
description = "Tool to generate `tzdb/src/generated.rs`"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.54"
convert_case = "0.5.0"
itertools = "0.10.3"
phf_codegen = "0.10.0"
tz-rs = "0.5.3"
