[package]
name = "tzdb"
version = "0.0.5"
edition = "2021"
authors = ["René Kijewski <crates.io@k6i.de>"]
repository = "https://github.com/Kijewski/tzdb"
description = "Static time zone information for tz-rs"
license = "Apache-2.0"
keywords = ["date", "time", "timezone", "zone", "calendar"]
categories = ["date-and-time"]
readme = "README.md"
rust-version = "1.57"

[dependencies]
once_cell = { version = "1.9.0", features = ["parking_lot", "race"] }
tz-rs = "0.5.3"

# optional dependencies
byte-slice-cast = { version = "1.2.0", optional = true }
document-features = { version = "=0.2.1", optional = true }
phf = { version = "0.10.1", optional = true }

[features]
default = ["by-name", "list"]
## enables [TimeZoneExt::from_db()]
##
by-name = ["phf", "byte-slice-cast"]
## enables [TimeZoneExt::names_in_db()]
##
list = []

# Internal feature, used when generating docs. *You* are not supposed to enable this feature!
docsrs = ["document-features", "default"]

[package.metadata.docs.rs]
features = ["docsrs"]
