[package]
name = "tzdb"
version = "0.0.1"
edition = "2021"
authors = ["René Kijewski <crates.io@k6i.de>"]
repository = "https://github.com/Kijewski/tzdb"
description = "Static time zone information for tz-rs"
license = "Apache-2.0"
keywords = ["date", "time", "timezone", "zone", "calendar"]
categories = ["date-and-time"]
readme = "README.md"

[dependencies]
once_cell = { version = "1.9.0", features = ["parking_lot", "race"] }
phf = { version = "0.10.1", default-features = false, features = ["macros"] }
tinystr = "0.5.0"
tz-rs = "0.5.3"
